name: Release

on:
  push:
    tags:
      - 'v*'  # This workflow will run when any tag starting with 'v' is pushed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing
      contents: write  # Required for GitHub release
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    # Build and publish the package to PyPI
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    
    # Extract changelog and create GitHub Release
    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v2

    # Create GitHub release
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.extract-release-notes.outputs.release_notes }}
        generate_release_notes: true